FROM postgres:14.8-alpine3.18

# Принимаем аргументы сборки
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD

# Устанавливаем переменные окружения
ENV POSTGRES_DB=${DB_NAME}
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}
